// Async persistence contracts for all domain aggregate types.

import Foundation

/// Stores and retrieves `InactivityEvent` records, scoped to a date range.
public protocol InactivityEventRepository: Sendable {

    /// Persists a new inactivity event.
    func save(_ event: InactivityEvent) async throws

    /// Returns all events whose `start` falls within [start, end).
    func fetch(from start: Date, to end: Date) async throws -> [InactivityEvent]
}

/// Stores and retrieves `LocationVisit` records, scoped to a date range.
public protocol LocationVisitRepository: Sendable {

    /// Persists a new location visit.
    func save(_ visit: LocationVisit) async throws

    /// Returns all visits whose `arrival` falls within [start, end).
    func fetch(from start: Date, to end: Date) async throws -> [LocationVisit]
}

/// Stores and retrieves `Recommendation` records, scoped to a date range.
public protocol RecommendationRepository: Sendable {

    /// Persists a recommendation generated by the engine.
    func save(_ recommendation: Recommendation) async throws

    /// Returns all recommendations whose `createdAt` falls within [start, end).
    func fetch(from start: Date, to end: Date) async throws -> [Recommendation]
}

/// Stores and retrieves `RecommendationDecision` records, keyed by recommendation ID.
public protocol RecommendationDecisionRepository: Sendable {

    /// Persists a user decision for a recommendation.
    func save(_ decision: RecommendationDecision) async throws

    /// Returns all decisions recorded for the given recommendation ID.
    func fetch(for recommendationId: UUID) async throws -> [RecommendationDecision]
}

/// Stores recurring inactivity patterns; only the most recent/best pattern is typically needed.
public protocol RecurringPatternRepository: Sendable {

    /// Persists a newly detected pattern, replacing any previous record with the same ID.
    func save(_ pattern: RecurringPattern) async throws

    /// Returns the single best-known pattern, or `nil` if none has been detected yet.
    func fetchLatest() async throws -> RecurringPattern?
}

/// Stores and retrieves the full catalogue of known green areas.
public protocol GreenAreaRepository: Sendable {

    func save(_ greenArea: GreenArea) async throws

    /// Returns all persisted green areas sorted by name.
    func fetchAll() async throws -> [GreenArea]
}

/// Synchronous load/save contract for user preferences.
///
/// Intentionally synchronous because `AppSettings` is lightweight and backed by
/// `UserDefaults`, which is always available on the main process.
public protocol SettingsRepository: Sendable {

    /// Loads the current settings, returning defaults for any missing keys.
    func load() -> AppSettings

    /// Persists the given settings.
    func save(_ settings: AppSettings)
}
