//
//  Item.swift
//  GreenRoute
//
//  Created by Freja Egelund Grønnemose on 28/02/2026.
//
// Xcode-generated template model. Not used by the application — retained as scaffolding.

import Foundation
import SwiftData

/// Placeholder SwiftData model generated by the Xcode project template.
/// Not wired into any feature of GreenRoute.
@Model
final class Item {
    var timestamp: Date

    init(timestamp: Date) {
        self.timestamp = timestamp
    }
}
